# APPLICATION CONFIGURATIONS
spring.application.name=spring-rest-project

# DATABASE CONFIGURATIONS
spring.datasource.url=jdbc:postgresql://localhost:5432/db_name
spring.datasource.username=postgres_username
spring.datasource.password=postgres_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIGURATIONS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# HTTP SESSION CONFIGURATIONS
spring.session.jdbc.initialize-schema=always

# INITIALIZER / SEED DATA PROPERTIES
spring.profiles.include=local
app.admin.username=${APP_ADMIN_USER}
app.admin.password=${APP_ADMIN_PASS}

# LOCALE MESSAGE CONFIGS
spring.messages.basename=messages/messages
spring.messages.fallback-to-system-locale=false
