spring.application.name=spring-rest-project

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_rest_project_db


spring.datasource.username=postgres
spring.datasource.password=CwkUeggEJq8tJj2QHsQK

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=false

spring.session.jdbc.initialize-schema=always