# APPLICATION CONFIGURATIONS
spring.application.name=sandbox-mcp
spring.profiles.include=local

# DATABASE CONFIGURATIONS
spring.datasource.url=${SANDBOX_DB_URL}
spring.datasource.username=${SANDBOX_DB_USER}
spring.datasource.password=${SANDBOX_DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# MCP SERVER CONFIGURATIONS
spring.ai.mcp.server.stdio=true
spring.main.web-application-type=none
spring.main.banner-mode=off
logging.level.root=WARN
spring.flyway.enabled=false
