# APPLICATION CONFIGURATIONS
spring.application.name=mcp-server

# DATABASE CONFIGURATIONS (READ-ONLY ROLE)
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_rest_project_db
spring.datasource.username=mcp_agent_readonly
spring.datasource.password=mcp_readonly_pword_123
spring.datasource.driver-class-name=org.postgresql.Driver

# MCP SERVER CONFIGURATIONS
spring.ai.mcp.server.stdio=true
spring.main.web-application-type=none
spring.main.banner-mode=off
logging.level.root=WARN
spring.flyway.enabled=false
